# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-23 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_topic_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': '主题相关', 'verbose_name_plural': '主题相关'},
        ),
    ]
